### ISSUE TITLE
filename does not accept concatenation

### ISSUE THREAD

**Issue by RyanMatheuZ** [EdisonJpp/react-export-html-table-to-excel#11]
With the following approach, the name of the file after downloading is "download", instead of the defined formatting

```
const handleDownloadExcel = () => {
    downloadExcel({
      fileName: `tabela-${sheetName?.toLowerCase()}`,
      sheet: sheetName || '',
      tablePayload: {
        header: tablePayload?.header || [],
        body: tablePayload?.body || [],
      },
    });
  };
```

**Comment by EdisonJpp** [comment]
HI @RyanMatheuZ 

I did here one example concatenating the file name and works.  

[url example](https://codesandbox.io/s/react-export-table-to-excel-sample-dvzkms?file=/src/samples/SampleMethod.tsx)
